load("@bazeldnf//bazeldnf:defs.bzl", "rpmtree")

rpmtree(
    name = "rpms-circular-triplet-package-1",
    rpms = [
        "@rpms-circular-triplet//package1",
    ],
)

rpmtree(
    name = "rpms-circular-triplet-package-2",
    rpms = [
        "@rpms-circular-triplet//package2",
    ],
)

rpmtree(
    name = "rpms-circular-triplet-package-3",
    rpms = [
        "@rpms-circular-triplet//package3",
    ],
)
