# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Binaries
        run: .github/workflows/build_assets.sh

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: tools/release/latest
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Fetch the built artifacts from build jobs above and extract into
      # ${GITHUB_WORKSPACE}/artifacts/bazeldnf_dawrin-amd64
      - uses: actions/download-artifact@v4

      - name: Prepare release
        run: .github/workflows/release_prep.sh > release_notes.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          files: |
            artifacts/*
            bazeldnf-*.tar.gz
          fail_on_unmatched_files: true
